/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ypCVhdEnIz9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export function kg-interface() {
  return (
    <div className="flex min-h-screen w-full">
      <div className="flex-1 bg-muted/40 p-6 md:p-8 lg:p-10">
        <div className="flex h-full flex-col gap-6">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold">Knowledge Graph Explorer</h1>
            <Button variant="outline" className="gap-2">
              <SearchIcon className="h-4 w-4" />
              Search
            </Button>
          </div>
          <div className="flex-1 rounded-lg bg-background p-6 shadow-lg">
            <div className="relative h-full w-full">
              <div className="absolute inset-0 flex items-center justify-center">
                <LoaderIcon className="h-12 w-12 animate-spin" />
              </div>
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="grid grid-cols-3 gap-4">
                  <div className="col-span-3 flex items-center justify-center">
                    <div className="h-10 w-10 rounded-full bg-primary" />
                  </div>
                  <div className="col-span-2 flex items-center justify-end">
                    <div className="h-8 w-8 rounded-full bg-secondary" />
                  </div>
                  <div className="col-span-1 flex items-center justify-start">
                    <div className="h-6 w-6 rounded-full bg-muted" />
                  </div>
                  <div className="col-span-1 flex items-center justify-end">
                    <div className="h-6 w-6 rounded-full bg-muted" />
                  </div>
                  <div className="col-span-2 flex items-center justify-start">
                    <div className="h-8 w-8 rounded-full bg-secondary" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex w-[600px] flex-col bg-background p-6 md:p-8 lg:p-10 shadow-lg">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-bold">Search</h2>
          <Button variant="outline" size="icon" className="h-8 w-8">
            <XIcon className="h-4 w-4" />
          </Button>
        </div>
        <div className="mt-6 flex-1">
          <Textarea
            placeholder="Enter your query..."
            className="h-full w-full resize-none rounded-lg border border-muted/50 p-4 text-sm focus:border-primary focus:outline-none"
          />
        </div>
        <div className="mt-6 grid grid-cols-2 gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Total Nodes</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold">12,345</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Total Edges</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold">45,678</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Activity</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold">3,456</div>
              <div className="text-sm text-muted-foreground">queries/day</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Connections</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold">98,765</div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

function LoaderIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2v4" />
      <path d="m16.2 7.8 2.9-2.9" />
      <path d="M18 12h4" />
      <path d="m16.2 16.2 2.9 2.9" />
      <path d="M12 18v4" />
      <path d="m4.9 19.1 2.9-2.9" />
      <path d="M2 12h4" />
      <path d="m4.9 4.9 2.9 2.9" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
